config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "games#new"

  resources :games, only: [:new, :create, :destroy] do
    collection do
      get 'play', to: "games#play", as: :play
      patch "add_score", to: "games#add_score", as: :add_score
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  DEFAULT_MAX_SCORE = 10_000

  has_many :players, dependent: :destroy
  belongs_to :current_player, class_name: "Player", optional: true
  belongs_to :next_player, class_name: "Player", optional: true

  accepts_nested_attributes_for :players, reject_if: :all_blank, allow_destroy: true

  validates :max_score, presence: true
  validates :players, length: { minimum: 1, message: 'should have at least 1 player.' }

  before_create :order_players

  def start!
    update(started_at: Time.zone.now)
  end

  def started?
    started_at.present?
  end

  def finish!
    update(finished_at: Time.zone.now)
  end

  def finished?
    finished_at.present?
  end

  def initialize_current_next_players!
    update!(current_player_id: first_player.id, next_player_id: first_player.next_player.id)
  end

  def first_player
    players.order(:order).first
  end

  private

  def order_players
    players.each_with_index do |player, index|
      player.order = index + 1
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game, optional: true

  validates :name, presence: true

  def next_player
    game.players.find_by(order: order + 1) || game.first_player
  end

  def points_to_success
    game.max_score - current_score
  end

  def won?
    current_score == max_score
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :current_game

  private

  def current_game
    @current_game ||= Game.find_by(id: REDIS_CLIENT.get(session[:current_anon_user_id]))
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    return redirect_to(play_games_path) if @current_game

    @game = Game.new
    @game.players.build
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      initialize_game_and_save_to_session
      redirect_to(play_games_path)
    else
      @game.players.build unless @game.players.any?
      render :new
    end
  end

  def play
    return redirect_to(new_game_path) unless @current_game

    @current_game.start! unless @current_game.started?
    @current_player = @current_game.current_player
  end

  def add_score
    return redirect_to(new_game_path) unless @current_game
    return next_player_and_redirect unless params[:player][:score].presence

    @current_player = @current_game.current_player
    new_score = @current_player.current_score + params[:player][:score].to_i
    if new_score > @current_game.max_score
      update_game_players
    elsif @current_player.update(current_score: new_score)
      if new_score == @current_game.max_score
        @current_game.finish!
      else
        update_game_players
      end
    end

    # raise
    redirect_to(play_games_path)
  end

  def destroy
    @current_game.destroy
    REDIS_CLIENT.del(session[:current_anon_user_id])
    redirect_to(new_game_path)
  end

  private

  def game_params
    params.require(:game).permit(:max_score, players_attributes: [:id, :name, :_destroy])
  end

  def initialize_game_and_save_to_session
    @game.initialize_current_next_players!
    session_id = session[:current_anon_user_id] || SecureRandom.urlsafe_base64(nil, false)
    session[:current_anon_user_id] = session_id
    REDIS_CLIENT.set(session_id, @game.id)
  end

  def update_game_players
    next_next_player = @current_game.next_player.next_player
    @current_game.update!(current_player_id: @current_game.next_player.id, next_player_id: next_next_player.id)
  end

  def next_player_and_redirect
    update_game_players
    redirect_to(play_games_path)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_finished.html.erb
<div>
  <h1 class="text-[35px] font-medium"><%= @current_player.name %> a gagné la partie !</h1>
</div>
<div class="w-full mt-9">
  <%= button_to("Recommencer", game_path(@current_game.id), method: :delete, class: "border-mygreen bg-mygreen text-black text-center cursor-pointer p-3 w-full") %>
</div>

app/views/games/_in_progress.html.erb
<div>
  <h1 class="text-[29px] font-medium flex flex-wrap">
    C'est au tour de <%= @current_player.name %>
  </h1>
  <p><%= button_to("Arrêter la partie", game_path(@current_game.id), method: :delete, class: "border-none bg-transparent text-sm text-neutral-500", data: { turbo_confirm: "Êtes-vous sûrs ?" }) %></p>
</div>
<div class="mt-9 bg-mygreen w-full px-5 py-6 text-black font-medium">
  <div>Score: <%= @current_player.current_score %>/<%= @current_game.max_score %></div>
  <div>Points restants: <%= @current_player.points_to_success %></div>
</div>
<div class="mt-3">
  <%= simple_form_for :player, url: add_score_games_path, method: :patch, data: { turbo: false } do |f| %>
    <%= f.input :score, label: "Score de la manche", as: :integer, required: false, class: "text-black" %>
    <%= f.submit "Valider", data: { disable_with: false }, class: "block w-full bg-mybeige text-center p-3 text-black mt-8 cursor-pointer" %>
  <% end %>
</div>

app/views/games/_player_fields.html.erb
<div class="nested-fields">
  <div class="flex items-end">
    <div class="<%= "flex-1" if f.index == 0 %>">
      <%= f.input :name, autocomplete: false %>
    </div>
    <% unless f.index == 0 %>
      <%= link_to_remove_association "X", f, class: "w-[42px] h-[42px] flex justify-center items-center bg-[#C8C1C1] text-white block mb-4 ml-1" %>
    <% end %>
  </div>
</div>

app/views/games/new.html.erb
<div>
  <h1 class="text-[35px] font-medium">Nouvelle partie</h1>
</div>
<%= simple_form_for @game, data: { turbo: false }, html: { autocomplete: 'off' } do |f| %>
  <div class="mt-9">
    <div class="bg-mygreen w-full px-5 py-6 text-black">
      <h3 class="font-medium text-[18px] mb-3">Options de jeu</h3>
      <div class="w-full">
        <%= f.input :max_score %>
      </div>
    </div>
    <div class="bg-mypink w-full px-5 py-6 text-black mt-9">
      <h3 class="font-medium text-[18px] mb-3">Joueurs</h3>
      <!-- Errors -->
      <% if @game.errors[:players].any? %>
        <% @game.errors[:players].each do |error_message| %>
          <span><%= error_message %></span>
        <% end %>
      <% end %>

      <div id="players">
        <%= f.simple_fields_for :players do |player| %>
          <%= render "player_fields", f: player %>
        <% end %>
        <div class="">
          <%= link_to_add_association 'Add player', f, :players, class: "bg-[#F3A4A0] block text-center w-full p-3" %>
        </div>
      </div>
    </div>
  </div>
  <div>
    <%= f.submit "Commencer", class: "block w-full bg-mybeige text-center p-3 mt-9 text-black cursor-pointer" %>
  </div>
<% end %>

app/views/games/play.html.erb
<% if @current_game.finished? %>
  <%= render "finished" %>
<% else %>
  <%= render "in_progress" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TenKayRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

  </head>

  <body>
    <main class="container mx-auto py-12 px-6">
      <%= yield %>
    </main>
  </body>
</html>